name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Trigger on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker to use the Docker daemon
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to DockerHub.
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
           time docker build -t harbeylefty17/devsecops:latest .

      # Push Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker push harbeylefty17/devsecops:latest
      
      # Configure AWS credentials for EKS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      # Setup kubectl for EKS
      - name: set up kubectl for EKS 
        run: |
          aws eks update-kubeconfig --region us-east-1 --name my-cluster

      # Deploy the app to Kubernetes using kubectl
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yml
        working-directory: ./kubernetes

      # Expose the application
      - name: Check if app is running
        run: |
          kubectl rollout status deployment/flask-app-deployment
          kubectl get pods
